/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDialog;

/**
 *
 * @author lukas.leja
 */
public class SizeChoosement extends javax.swing.JPanel {

    /**
     * Creates new form SizeChoosement
     */
    public SizeChoosement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonSize4 = new javax.swing.JButton();
        ButtonSize8 = new javax.swing.JButton();
        ButtonSize16 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N

        ButtonSize4.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        ButtonSize4.setText("4x4");
        ButtonSize4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSize4ActionPerformed(evt);
            }
        });

        ButtonSize8.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        ButtonSize8.setText("9x9");
        ButtonSize8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSize8ActionPerformed(evt);
            }
        });

        ButtonSize16.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        ButtonSize16.setText("16x16");
        ButtonSize16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSize16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ButtonSize4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ButtonSize8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ButtonSize16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSize4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSize8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSize16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSize8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSize8ActionPerformed
        control.main.window.remove(this);
        control.main.window.setSize(410,460);
        control.main.sdkImp = new view.SudokuImportment();
        control.main.window.add(control.main.sdkImp);
        control.main.size = 9;
    }//GEN-LAST:event_ButtonSize8ActionPerformed

    private void ButtonSize4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSize4ActionPerformed
        control.main.window.remove(this);
        control.main.window.setSize(340,360);
        control.main.sdkImp4 = new view.SudokuImportment4x4();
        control.main.window.add(control.main.sdkImp4);
        control.main.size = 4;
    }//GEN-LAST:event_ButtonSize4ActionPerformed

    private void ButtonSize16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSize16ActionPerformed
        control.main.window.remove(this);
        control.main.window.setSize(600,660);
        control.main.sdkImp16 = new view.SudokuImportment16x16();
        control.main.window.add(control.main.sdkImp16);
        control.main.size = 16;
    }//GEN-LAST:event_ButtonSize16ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSize16;
    private javax.swing.JButton ButtonSize4;
    private javax.swing.JButton ButtonSize8;
    // End of variables declaration//GEN-END:variables
}
