/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.accessibility.AccessibleContext;
import javax.swing.JTextPane;

/**
 *
 * @author joshu
 */
public class SudokuExportment extends javax.swing.JPanel {

    /**
     * Creates new form SudokuExportment
     */
    public SudokuExportment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ImportImp = new javax.swing.JButton();
        L1x1 = new javax.swing.JTextPane();
        L1x2 = new javax.swing.JTextPane();
        L1x3 = new javax.swing.JTextPane();
        L1x4 = new javax.swing.JTextPane();
        L1x5 = new javax.swing.JTextPane();
        L1x6 = new javax.swing.JTextPane();
        L1x7 = new javax.swing.JTextPane();
        L1x8 = new javax.swing.JTextPane();
        L1x9 = new javax.swing.JTextPane();
        L2x1 = new javax.swing.JTextPane();
        L2x2 = new javax.swing.JTextPane();
        L2x3 = new javax.swing.JTextPane();
        L2x4 = new javax.swing.JTextPane();
        L2x5 = new javax.swing.JTextPane();
        L2x6 = new javax.swing.JTextPane();
        L2x7 = new javax.swing.JTextPane();
        L2x8 = new javax.swing.JTextPane();
        L2x9 = new javax.swing.JTextPane();
        L3x1 = new javax.swing.JTextPane();
        L3x2 = new javax.swing.JTextPane();
        L3x3 = new javax.swing.JTextPane();
        L3x4 = new javax.swing.JTextPane();
        L3x5 = new javax.swing.JTextPane();
        L3x6 = new javax.swing.JTextPane();
        L3x7 = new javax.swing.JTextPane();
        L3x8 = new javax.swing.JTextPane();
        L3x9 = new javax.swing.JTextPane();
        L4x1 = new javax.swing.JTextPane();
        L4x2 = new javax.swing.JTextPane();
        L4x3 = new javax.swing.JTextPane();
        L4x4 = new javax.swing.JTextPane();
        L4x5 = new javax.swing.JTextPane();
        L4x6 = new javax.swing.JTextPane();
        L4x7 = new javax.swing.JTextPane();
        L4x8 = new javax.swing.JTextPane();
        L4x9 = new javax.swing.JTextPane();
        L5x1 = new javax.swing.JTextPane();
        L5x2 = new javax.swing.JTextPane();
        L5x3 = new javax.swing.JTextPane();
        L5x4 = new javax.swing.JTextPane();
        L5x5 = new javax.swing.JTextPane();
        L5x6 = new javax.swing.JTextPane();
        L5x7 = new javax.swing.JTextPane();
        L5x8 = new javax.swing.JTextPane();
        L5x9 = new javax.swing.JTextPane();
        L6x1 = new javax.swing.JTextPane();
        L6x2 = new javax.swing.JTextPane();
        L6x3 = new javax.swing.JTextPane();
        L6x4 = new javax.swing.JTextPane();
        L6x5 = new javax.swing.JTextPane();
        L6x6 = new javax.swing.JTextPane();
        L6x7 = new javax.swing.JTextPane();
        L6x8 = new javax.swing.JTextPane();
        L6x9 = new javax.swing.JTextPane();
        L7x1 = new javax.swing.JTextPane();
        L7x2 = new javax.swing.JTextPane();
        L7x3 = new javax.swing.JTextPane();
        L7x4 = new javax.swing.JTextPane();
        L7x5 = new javax.swing.JTextPane();
        L7x6 = new javax.swing.JTextPane();
        L7x7 = new javax.swing.JTextPane();
        L7x8 = new javax.swing.JTextPane();
        L7x9 = new javax.swing.JTextPane();
        L8x1 = new javax.swing.JTextPane();
        L8x2 = new javax.swing.JTextPane();
        L8x3 = new javax.swing.JTextPane();
        L8x4 = new javax.swing.JTextPane();
        L8x5 = new javax.swing.JTextPane();
        L8x6 = new javax.swing.JTextPane();
        L8x7 = new javax.swing.JTextPane();
        L8x8 = new javax.swing.JTextPane();
        L8x9 = new javax.swing.JTextPane();
        L9x1 = new javax.swing.JTextPane();
        L9x2 = new javax.swing.JTextPane();
        L9x3 = new javax.swing.JTextPane();
        L9x4 = new javax.swing.JTextPane();
        L9x5 = new javax.swing.JTextPane();
        L9x6 = new javax.swing.JTextPane();
        L9x7 = new javax.swing.JTextPane();
        L9x8 = new javax.swing.JTextPane();
        L9x9 = new javax.swing.JTextPane();

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Neues Sudoku?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel2.setText("9x9");

        ImportImp.setText("Export");

        L1x1.setEditable(false);
        L1x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x2.setEditable(false);
        L1x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x3.setEditable(false);
        L1x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x4.setEditable(false);
        L1x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x5.setEditable(false);
        L1x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x6.setEditable(false);
        L1x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x7.setEditable(false);
        L1x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x8.setEditable(false);
        L1x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x9.setEditable(false);
        L1x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x1.setEditable(false);
        L2x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x2.setEditable(false);
        L2x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x3.setEditable(false);
        L2x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x4.setEditable(false);
        L2x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x5.setEditable(false);
        L2x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x6.setEditable(false);
        L2x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x7.setEditable(false);
        L2x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x8.setEditable(false);
        L2x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x9.setEditable(false);
        L2x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x1.setEditable(false);
        L3x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x2.setEditable(false);
        L3x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x3.setEditable(false);
        L3x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x4.setEditable(false);
        L3x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x5.setEditable(false);
        L3x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x6.setEditable(false);
        L3x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x7.setEditable(false);
        L3x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x8.setEditable(false);
        L3x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x9.setEditable(false);
        L3x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x1.setEditable(false);
        L4x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x2.setEditable(false);
        L4x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x3.setEditable(false);
        L4x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x4.setEditable(false);
        L4x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x5.setEditable(false);
        L4x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x6.setEditable(false);
        L4x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x7.setEditable(false);
        L4x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x8.setEditable(false);
        L4x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x9.setEditable(false);
        L4x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x1.setEditable(false);
        L5x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x2.setEditable(false);
        L5x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x3.setEditable(false);
        L5x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x4.setEditable(false);
        L5x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x5.setEditable(false);
        L5x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x6.setEditable(false);
        L5x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x7.setEditable(false);
        L5x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x8.setEditable(false);
        L5x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x9.setEditable(false);
        L5x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x1.setEditable(false);
        L6x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x2.setEditable(false);
        L6x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x3.setEditable(false);
        L6x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x4.setEditable(false);
        L6x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x5.setEditable(false);
        L6x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x6.setEditable(false);
        L6x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x7.setEditable(false);
        L6x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x8.setEditable(false);
        L6x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x9.setEditable(false);
        L6x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x1.setEditable(false);
        L7x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x2.setEditable(false);
        L7x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x3.setEditable(false);
        L7x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x4.setEditable(false);
        L7x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x5.setEditable(false);
        L7x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x6.setEditable(false);
        L7x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x7.setEditable(false);
        L7x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x8.setEditable(false);
        L7x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x9.setEditable(false);
        L7x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x1.setEditable(false);
        L8x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x2.setEditable(false);
        L8x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x3.setEditable(false);
        L8x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x4.setEditable(false);
        L8x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x5.setEditable(false);
        L8x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x6.setEditable(false);
        L8x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x7.setEditable(false);
        L8x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x8.setEditable(false);
        L8x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x9.setEditable(false);
        L8x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x1.setEditable(false);
        L9x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x2.setEditable(false);
        L9x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x3.setEditable(false);
        L9x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x4.setEditable(false);
        L9x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x5.setEditable(false);
        L9x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x6.setEditable(false);
        L9x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x7.setEditable(false);
        L9x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x8.setEditable(false);
        L9x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x9.setEditable(false);
        L9x9.setMinimumSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(108, 108, 108)
                .addComponent(ImportImp)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L7x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L7x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L7x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L6x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L6x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L6x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L5x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L5x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L5x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L4x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L4x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L4x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L8x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L8x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L8x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L9x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L9x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L9x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(10, 10, 10)
                            .addComponent(L9x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L9x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L9x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L7x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L7x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L7x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L6x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L6x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L6x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L5x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L5x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L5x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L4x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L4x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L3x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L3x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L2x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L2x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L8x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L8x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L8x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L1x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(L1x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L9x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L9x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L9x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L7x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L7x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L7x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L6x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L6x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L6x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L5x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L5x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L5x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L4x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L4x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L4x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L3x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L3x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L3x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L2x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L2x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L2x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L1x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L1x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L1x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(L8x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L8x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L8x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(82, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImportImp)
                    .addComponent(jLabel2))
                .addGap(264, 264, 264)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L1x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L1x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L1x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L1x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L1x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L1x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L1x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L2x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L2x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L2x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L2x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L2x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L2x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L2x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L3x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L3x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L3x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L3x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L3x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L3x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L3x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L4x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L4x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L4x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L4x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L4x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L4x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L4x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L4x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L5x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L5x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L5x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L5x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L5x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L5x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L5x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L5x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L5x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L6x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L6x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L6x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L6x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L6x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L6x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L6x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L6x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L6x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L7x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L7x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L7x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L7x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L7x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L7x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L7x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L7x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L7x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L8x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L8x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L8x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L8x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L8x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L8x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L8x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L8x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L8x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L9x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L9x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L9x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L9x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L9x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L9x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L9x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L9x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L9x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        control.main.window.remove(this);
        control.main.window.setSize(450,300);
        control.main.szeCh = new view.SizeChoosement();
        control.main.window.add(control.main.szeCh);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        control.main.window.remove(this);
        control.main.window.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImportImp;
    private javax.swing.JTextPane L1x1;
    private javax.swing.JTextPane L1x2;
    private javax.swing.JTextPane L1x3;
    private javax.swing.JTextPane L1x4;
    private javax.swing.JTextPane L1x5;
    private javax.swing.JTextPane L1x6;
    private javax.swing.JTextPane L1x7;
    private javax.swing.JTextPane L1x8;
    private javax.swing.JTextPane L1x9;
    private javax.swing.JTextPane L2x1;
    private javax.swing.JTextPane L2x2;
    private javax.swing.JTextPane L2x3;
    private javax.swing.JTextPane L2x4;
    private javax.swing.JTextPane L2x5;
    private javax.swing.JTextPane L2x6;
    private javax.swing.JTextPane L2x7;
    private javax.swing.JTextPane L2x8;
    private javax.swing.JTextPane L2x9;
    private javax.swing.JTextPane L3x1;
    private javax.swing.JTextPane L3x2;
    private javax.swing.JTextPane L3x3;
    private javax.swing.JTextPane L3x4;
    private javax.swing.JTextPane L3x5;
    private javax.swing.JTextPane L3x6;
    private javax.swing.JTextPane L3x7;
    private javax.swing.JTextPane L3x8;
    private javax.swing.JTextPane L3x9;
    private javax.swing.JTextPane L4x1;
    private javax.swing.JTextPane L4x2;
    private javax.swing.JTextPane L4x3;
    private javax.swing.JTextPane L4x4;
    private javax.swing.JTextPane L4x5;
    private javax.swing.JTextPane L4x6;
    private javax.swing.JTextPane L4x7;
    private javax.swing.JTextPane L4x8;
    private javax.swing.JTextPane L4x9;
    private javax.swing.JTextPane L5x1;
    private javax.swing.JTextPane L5x2;
    private javax.swing.JTextPane L5x3;
    private javax.swing.JTextPane L5x4;
    private javax.swing.JTextPane L5x5;
    private javax.swing.JTextPane L5x6;
    private javax.swing.JTextPane L5x7;
    private javax.swing.JTextPane L5x8;
    private javax.swing.JTextPane L5x9;
    private javax.swing.JTextPane L6x1;
    private javax.swing.JTextPane L6x2;
    private javax.swing.JTextPane L6x3;
    private javax.swing.JTextPane L6x4;
    private javax.swing.JTextPane L6x5;
    private javax.swing.JTextPane L6x6;
    private javax.swing.JTextPane L6x7;
    private javax.swing.JTextPane L6x8;
    private javax.swing.JTextPane L6x9;
    private javax.swing.JTextPane L7x1;
    private javax.swing.JTextPane L7x2;
    private javax.swing.JTextPane L7x3;
    private javax.swing.JTextPane L7x4;
    private javax.swing.JTextPane L7x5;
    private javax.swing.JTextPane L7x6;
    private javax.swing.JTextPane L7x7;
    private javax.swing.JTextPane L7x8;
    private javax.swing.JTextPane L7x9;
    private javax.swing.JTextPane L8x1;
    private javax.swing.JTextPane L8x2;
    private javax.swing.JTextPane L8x3;
    private javax.swing.JTextPane L8x4;
    private javax.swing.JTextPane L8x5;
    private javax.swing.JTextPane L8x6;
    private javax.swing.JTextPane L8x7;
    private javax.swing.JTextPane L8x8;
    private javax.swing.JTextPane L8x9;
    private javax.swing.JTextPane L9x1;
    private javax.swing.JTextPane L9x2;
    private javax.swing.JTextPane L9x3;
    private javax.swing.JTextPane L9x4;
    private javax.swing.JTextPane L9x5;
    private javax.swing.JTextPane L9x6;
    private javax.swing.JTextPane L9x7;
    private javax.swing.JTextPane L9x8;
    private javax.swing.JTextPane L9x9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public JTextPane getL1x1() {
        return L1x1;
    }

    public void setL1x1(JTextPane L1x1) {
        this.L1x1 = L1x1;
    }

    public JTextPane getL1x2() {
        return L1x2;
    }

    public void setL1x2(JTextPane L1x2) {
        this.L1x2 = L1x2;
    }

    public JTextPane getL1x3() {
        return L1x3;
    }

    public void setL1x3(JTextPane L1x3) {
        this.L1x3 = L1x3;
    }

    public JTextPane getL1x4() {
        return L1x4;
    }

    public void setL1x4(JTextPane L1x4) {
        this.L1x4 = L1x4;
    }

    public JTextPane getL1x5() {
        return L1x5;
    }

    public void setL1x5(JTextPane L1x5) {
        this.L1x5 = L1x5;
    }

    public JTextPane getL1x6() {
        return L1x6;
    }

    public void setL1x6(JTextPane L1x6) {
        this.L1x6 = L1x6;
    }

    public JTextPane getL1x7() {
        return L1x7;
    }

    public void setL1x7(JTextPane L1x7) {
        this.L1x7 = L1x7;
    }

    public JTextPane getL1x8() {
        return L1x8;
    }

    public void setL1x8(JTextPane L1x8) {
        this.L1x8 = L1x8;
    }

    public JTextPane getL1x9() {
        return L1x9;
    }

    public void setL1x9(JTextPane L1x9) {
        this.L1x9 = L1x9;
    }

    public JTextPane getL2x1() {
        return L2x1;
    }

    public void setL2x1(JTextPane L2x1) {
        this.L2x1 = L2x1;
    }

    public JTextPane getL2x2() {
        return L2x2;
    }

    public void setL2x2(JTextPane L2x2) {
        this.L2x2 = L2x2;
    }

    public JTextPane getL2x3() {
        return L2x3;
    }

    public void setL2x3(JTextPane L2x3) {
        this.L2x3 = L2x3;
    }

    public JTextPane getL2x4() {
        return L2x4;
    }

    public void setL2x4(JTextPane L2x4) {
        this.L2x4 = L2x4;
    }

    public JTextPane getL2x5() {
        return L2x5;
    }

    public void setL2x5(JTextPane L2x5) {
        this.L2x5 = L2x5;
    }

    public JTextPane getL2x6() {
        return L2x6;
    }

    public void setL2x6(JTextPane L2x6) {
        this.L2x6 = L2x6;
    }

    public JTextPane getL2x7() {
        return L2x7;
    }

    public void setL2x7(JTextPane L2x7) {
        this.L2x7 = L2x7;
    }

    public JTextPane getL2x8() {
        return L2x8;
    }

    public void setL2x8(JTextPane L2x8) {
        this.L2x8 = L2x8;
    }

    public JTextPane getL2x9() {
        return L2x9;
    }

    public void setL2x9(JTextPane L2x9) {
        this.L2x9 = L2x9;
    }

    public JTextPane getL3x1() {
        return L3x1;
    }

    public void setL3x1(JTextPane L3x1) {
        this.L3x1 = L3x1;
    }

    public JTextPane getL3x2() {
        return L3x2;
    }

    public void setL3x2(JTextPane L3x2) {
        this.L3x2 = L3x2;
    }

    public JTextPane getL3x3() {
        return L3x3;
    }

    public void setL3x3(JTextPane L3x3) {
        this.L3x3 = L3x3;
    }

    public JTextPane getL3x4() {
        return L3x4;
    }

    public void setL3x4(JTextPane L3x4) {
        this.L3x4 = L3x4;
    }

    public JTextPane getL3x5() {
        return L3x5;
    }

    public void setL3x5(JTextPane L3x5) {
        this.L3x5 = L3x5;
    }

    public JTextPane getL3x6() {
        return L3x6;
    }

    public void setL3x6(JTextPane L3x6) {
        this.L3x6 = L3x6;
    }

    public JTextPane getL3x7() {
        return L3x7;
    }

    public void setL3x7(JTextPane L3x7) {
        this.L3x7 = L3x7;
    }

    public JTextPane getL3x8() {
        return L3x8;
    }

    public void setL3x8(JTextPane L3x8) {
        this.L3x8 = L3x8;
    }

    public JTextPane getL3x9() {
        return L3x9;
    }

    public void setL3x9(JTextPane L3x9) {
        this.L3x9 = L3x9;
    }

    public JTextPane getL4x1() {
        return L4x1;
    }

    public void setL4x1(JTextPane L4x1) {
        this.L4x1 = L4x1;
    }

    public JTextPane getL4x2() {
        return L4x2;
    }

    public void setL4x2(JTextPane L4x2) {
        this.L4x2 = L4x2;
    }

    public JTextPane getL4x3() {
        return L4x3;
    }

    public void setL4x3(JTextPane L4x3) {
        this.L4x3 = L4x3;
    }

    public JTextPane getL4x4() {
        return L4x4;
    }

    public void setL4x4(JTextPane L4x4) {
        this.L4x4 = L4x4;
    }

    public JTextPane getL4x5() {
        return L4x5;
    }

    public void setL4x5(JTextPane L4x5) {
        this.L4x5 = L4x5;
    }

    public JTextPane getL4x6() {
        return L4x6;
    }

    public void setL4x6(JTextPane L4x6) {
        this.L4x6 = L4x6;
    }

    public JTextPane getL4x7() {
        return L4x7;
    }

    public void setL4x7(JTextPane L4x7) {
        this.L4x7 = L4x7;
    }

    public JTextPane getL4x8() {
        return L4x8;
    }

    public void setL4x8(JTextPane L4x8) {
        this.L4x8 = L4x8;
    }

    public JTextPane getL4x9() {
        return L4x9;
    }

    public void setL4x9(JTextPane L4x9) {
        this.L4x9 = L4x9;
    }

    public JTextPane getL5x1() {
        return L5x1;
    }

    public void setL5x1(JTextPane L5x1) {
        this.L5x1 = L5x1;
    }

    public JTextPane getL5x2() {
        return L5x2;
    }

    public void setL5x2(JTextPane L5x2) {
        this.L5x2 = L5x2;
    }

    public JTextPane getL5x3() {
        return L5x3;
    }

    public void setL5x3(JTextPane L5x3) {
        this.L5x3 = L5x3;
    }

    public JTextPane getL5x4() {
        return L5x4;
    }

    public void setL5x4(JTextPane L5x4) {
        this.L5x4 = L5x4;
    }

    public JTextPane getL5x5() {
        return L5x5;
    }

    public void setL5x5(JTextPane L5x5) {
        this.L5x5 = L5x5;
    }

    public JTextPane getL5x6() {
        return L5x6;
    }

    public void setL5x6(JTextPane L5x6) {
        this.L5x6 = L5x6;
    }

    public JTextPane getL5x7() {
        return L5x7;
    }

    public void setL5x7(JTextPane L5x7) {
        this.L5x7 = L5x7;
    }

    public JTextPane getL5x8() {
        return L5x8;
    }

    public void setL5x8(JTextPane L5x8) {
        this.L5x8 = L5x8;
    }

    public JTextPane getL5x9() {
        return L5x9;
    }

    public void setL5x9(JTextPane L5x9) {
        this.L5x9 = L5x9;
    }

    public JTextPane getL6x1() {
        return L6x1;
    }

    public void setL6x1(JTextPane L6x1) {
        this.L6x1 = L6x1;
    }

    public JTextPane getL6x2() {
        return L6x2;
    }

    public void setL6x2(JTextPane L6x2) {
        this.L6x2 = L6x2;
    }

    public JTextPane getL6x3() {
        return L6x3;
    }

    public void setL6x3(JTextPane L6x3) {
        this.L6x3 = L6x3;
    }

    public JTextPane getL6x4() {
        return L6x4;
    }

    public void setL6x4(JTextPane L6x4) {
        this.L6x4 = L6x4;
    }

    public JTextPane getL6x5() {
        return L6x5;
    }

    public void setL6x5(JTextPane L6x5) {
        this.L6x5 = L6x5;
    }

    public JTextPane getL6x6() {
        return L6x6;
    }

    public void setL6x6(JTextPane L6x6) {
        this.L6x6 = L6x6;
    }

    public JTextPane getL6x7() {
        return L6x7;
    }

    public void setL6x7(JTextPane L6x7) {
        this.L6x7 = L6x7;
    }

    public JTextPane getL6x8() {
        return L6x8;
    }

    public void setL6x8(JTextPane L6x8) {
        this.L6x8 = L6x8;
    }

    public JTextPane getL6x9() {
        return L6x9;
    }

    public void setL6x9(JTextPane L6x9) {
        this.L6x9 = L6x9;
    }

    public JTextPane getL7x1() {
        return L7x1;
    }

    public void setL7x1(JTextPane L7x1) {
        this.L7x1 = L7x1;
    }

    public JTextPane getL7x2() {
        return L7x2;
    }

    public void setL7x2(JTextPane L7x2) {
        this.L7x2 = L7x2;
    }

    public JTextPane getL7x3() {
        return L7x3;
    }

    public void setL7x3(JTextPane L7x3) {
        this.L7x3 = L7x3;
    }

    public JTextPane getL7x4() {
        return L7x4;
    }

    public void setL7x4(JTextPane L7x4) {
        this.L7x4 = L7x4;
    }

    public JTextPane getL7x5() {
        return L7x5;
    }

    public void setL7x5(JTextPane L7x5) {
        this.L7x5 = L7x5;
    }

    public JTextPane getL7x6() {
        return L7x6;
    }

    public void setL7x6(JTextPane L7x6) {
        this.L7x6 = L7x6;
    }

    public JTextPane getL7x7() {
        return L7x7;
    }

    public void setL7x7(JTextPane L7x7) {
        this.L7x7 = L7x7;
    }

    public JTextPane getL7x8() {
        return L7x8;
    }

    public void setL7x8(JTextPane L7x8) {
        this.L7x8 = L7x8;
    }

    public JTextPane getL7x9() {
        return L7x9;
    }

    public void setL7x9(JTextPane L7x9) {
        this.L7x9 = L7x9;
    }

    public JTextPane getL8x1() {
        return L8x1;
    }

    public void setL8x1(JTextPane L8x1) {
        this.L8x1 = L8x1;
    }

    public JTextPane getL8x2() {
        return L8x2;
    }

    public void setL8x2(JTextPane L8x2) {
        this.L8x2 = L8x2;
    }

    public JTextPane getL8x3() {
        return L8x3;
    }

    public void setL8x3(JTextPane L8x3) {
        this.L8x3 = L8x3;
    }

    public JTextPane getL8x4() {
        return L8x4;
    }

    public void setL8x4(JTextPane L8x4) {
        this.L8x4 = L8x4;
    }

    public JTextPane getL8x5() {
        return L8x5;
    }

    public void setL8x5(JTextPane L8x5) {
        this.L8x5 = L8x5;
    }

    public JTextPane getL8x6() {
        return L8x6;
    }

    public void setL8x6(JTextPane L8x6) {
        this.L8x6 = L8x6;
    }

    public JTextPane getL8x7() {
        return L8x7;
    }

    public void setL8x7(JTextPane L8x7) {
        this.L8x7 = L8x7;
    }

    public JTextPane getL8x8() {
        return L8x8;
    }

    public void setL8x8(JTextPane L8x8) {
        this.L8x8 = L8x8;
    }

    public JTextPane getL8x9() {
        return L8x9;
    }

    public void setL8x9(JTextPane L8x9) {
        this.L8x9 = L8x9;
    }

    public JTextPane getL9x1() {
        return L9x1;
    }

    public void setL9x1(JTextPane L9x1) {
        this.L9x1 = L9x1;
    }

    public JTextPane getL9x2() {
        return L9x2;
    }

    public void setL9x2(JTextPane L9x2) {
        this.L9x2 = L9x2;
    }

    public JTextPane getL9x3() {
        return L9x3;
    }

    public void setL9x3(JTextPane L9x3) {
        this.L9x3 = L9x3;
    }

    public JTextPane getL9x4() {
        return L9x4;
    }

    public void setL9x4(JTextPane L9x4) {
        this.L9x4 = L9x4;
    }

    public JTextPane getL9x5() {
        return L9x5;
    }

    public void setL9x5(JTextPane L9x5) {
        this.L9x5 = L9x5;
    }

    public JTextPane getL9x6() {
        return L9x6;
    }

    public void setL9x6(JTextPane L9x6) {
        this.L9x6 = L9x6;
    }

    public JTextPane getL9x7() {
        return L9x7;
    }

    public void setL9x7(JTextPane L9x7) {
        this.L9x7 = L9x7;
    }

    public JTextPane getL9x8() {
        return L9x8;
    }

    public void setL9x8(JTextPane L9x8) {
        this.L9x8 = L9x8;
    }

    public JTextPane getL9x9() {
        return L9x9;
    }

    public void setL9x9(JTextPane L9x9) {
        this.L9x9 = L9x9;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }


}
