/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDialog;

/**
 *
 * @author lukas.leja
 */
public class SudokuImportment extends javax.swing.JPanel {

    /**
     * Creates new form SudokuImportment
     */
    public SudokuImportment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZurückImp = new javax.swing.JButton();
        ImportImp = new javax.swing.JButton();
        LösenImp = new javax.swing.JButton();
        L1x1 = new javax.swing.JTextPane();
        L1x2 = new javax.swing.JTextPane();
        L1x3 = new javax.swing.JTextPane();
        L1x4 = new javax.swing.JTextPane();
        L1x5 = new javax.swing.JTextPane();
        L1x6 = new javax.swing.JTextPane();
        L1x7 = new javax.swing.JTextPane();
        L1x8 = new javax.swing.JTextPane();
        L1x9 = new javax.swing.JTextPane();
        L2x1 = new javax.swing.JTextPane();
        L2x2 = new javax.swing.JTextPane();
        L2x3 = new javax.swing.JTextPane();
        L2x4 = new javax.swing.JTextPane();
        L2x5 = new javax.swing.JTextPane();
        L2x6 = new javax.swing.JTextPane();
        L2x7 = new javax.swing.JTextPane();
        L2x8 = new javax.swing.JTextPane();
        L2x9 = new javax.swing.JTextPane();
        L3x1 = new javax.swing.JTextPane();
        L3x2 = new javax.swing.JTextPane();
        L3x3 = new javax.swing.JTextPane();
        L3x4 = new javax.swing.JTextPane();
        L3x5 = new javax.swing.JTextPane();
        L3x6 = new javax.swing.JTextPane();
        L3x7 = new javax.swing.JTextPane();
        L3x8 = new javax.swing.JTextPane();
        L3x9 = new javax.swing.JTextPane();
        L4x1 = new javax.swing.JTextPane();
        L4x2 = new javax.swing.JTextPane();
        L4x3 = new javax.swing.JTextPane();
        L4x4 = new javax.swing.JTextPane();
        L4x5 = new javax.swing.JTextPane();
        L4x6 = new javax.swing.JTextPane();
        L4x7 = new javax.swing.JTextPane();
        L4x8 = new javax.swing.JTextPane();
        L4x9 = new javax.swing.JTextPane();
        L5x1 = new javax.swing.JTextPane();
        L5x2 = new javax.swing.JTextPane();
        L5x3 = new javax.swing.JTextPane();
        L5x4 = new javax.swing.JTextPane();
        L5x5 = new javax.swing.JTextPane();
        L5x6 = new javax.swing.JTextPane();
        L5x7 = new javax.swing.JTextPane();
        L5x8 = new javax.swing.JTextPane();
        L5x9 = new javax.swing.JTextPane();
        L6x1 = new javax.swing.JTextPane();
        L6x2 = new javax.swing.JTextPane();
        L6x3 = new javax.swing.JTextPane();
        L6x4 = new javax.swing.JTextPane();
        L6x5 = new javax.swing.JTextPane();
        L6x6 = new javax.swing.JTextPane();
        L6x7 = new javax.swing.JTextPane();
        L6x8 = new javax.swing.JTextPane();
        L6x9 = new javax.swing.JTextPane();
        L7x1 = new javax.swing.JTextPane();
        L7x2 = new javax.swing.JTextPane();
        L7x3 = new javax.swing.JTextPane();
        L7x4 = new javax.swing.JTextPane();
        L7x5 = new javax.swing.JTextPane();
        L7x6 = new javax.swing.JTextPane();
        L7x7 = new javax.swing.JTextPane();
        L7x8 = new javax.swing.JTextPane();
        L7x9 = new javax.swing.JTextPane();
        L8x1 = new javax.swing.JTextPane();
        L8x2 = new javax.swing.JTextPane();
        L8x3 = new javax.swing.JTextPane();
        L8x4 = new javax.swing.JTextPane();
        L8x5 = new javax.swing.JTextPane();
        L8x6 = new javax.swing.JTextPane();
        L8x7 = new javax.swing.JTextPane();
        L8x8 = new javax.swing.JTextPane();
        L8x9 = new javax.swing.JTextPane();
        L9x1 = new javax.swing.JTextPane();
        L9x2 = new javax.swing.JTextPane();
        L9x3 = new javax.swing.JTextPane();
        L9x4 = new javax.swing.JTextPane();
        L9x5 = new javax.swing.JTextPane();
        L9x6 = new javax.swing.JTextPane();
        L9x7 = new javax.swing.JTextPane();
        L9x8 = new javax.swing.JTextPane();
        L9x9 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        ZurückImp.setText("Zurück");
        ZurückImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZurückImpActionPerformed(evt);
            }
        });

        ImportImp.setText("Import");

        LösenImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Lösen Knopf text klein.png"))); // NOI18N
        LösenImp.setBorder(null);
        LösenImp.setBorderPainted(false);
        LösenImp.setContentAreaFilled(false);
        LösenImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LösenImpActionPerformed(evt);
            }
        });

        L1x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L1x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L2x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L3x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L4x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L5x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L6x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L7x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L8x9.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x1.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x2.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x3.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x4.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x5.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x6.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x7.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x8.setMinimumSize(new java.awt.Dimension(24, 24));

        L9x9.setMinimumSize(new java.awt.Dimension(24, 24));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jLabel1.setText("9x9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ZurückImp)
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImportImp)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L7x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L7x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L7x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L6x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L6x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L6x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L5x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L5x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L5x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L4x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L4x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L4x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L8x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L8x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L8x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L9x1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L9x2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L9x3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addComponent(L9x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L9x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L9x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L7x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L7x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L7x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L6x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L6x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L6x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L5x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L5x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L5x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L4x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L4x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L3x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L3x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L2x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L2x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L8x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L8x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L8x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L1x5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L1x6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L9x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L9x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L9x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L7x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L7x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L7x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L6x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L6x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L6x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L5x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L5x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L5x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L4x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L4x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L4x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L3x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L3x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L3x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L2x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L2x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L2x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L1x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L1x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L1x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L8x7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L8x8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L8x9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LösenImp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(0, 82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZurückImp)
                    .addComponent(ImportImp)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L3x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L4x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L5x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L6x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L7x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L8x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L9x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9x5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9x6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9x7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9x8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9x9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(LösenImp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ZurückImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZurückImpActionPerformed
        control.main.window.remove(this);
        control.main.window.setSize(450,300);
        control.main.szeCh = new view.SizeChoosement();
        control.main.window.add(control.main.szeCh);        
        control.main.window.setVisible(true);
    }//GEN-LAST:event_ZurückImpActionPerformed

    private void LösenImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LösenImpActionPerformed
        control.main.window.remove(this);
        control.main.sdkExp9 = new view.SudokuExportment();
        control.main.window.add(control.main.sdkExp9);

        control.main.sudokuInitialisieren((short)9);
        
        control.main.zelleVeraendern((short)0, (short)0, L1x1.getText());
        control.main.zelleVeraendern((short)0, (short)1, L1x2.getText());
        control.main.zelleVeraendern((short)0, (short)2, L1x3.getText());
        control.main.zelleVeraendern((short)0, (short)3, L1x4.getText());
        control.main.zelleVeraendern((short)0, (short)4, L1x5.getText());
        control.main.zelleVeraendern((short)0, (short)5, L1x6.getText());
        control.main.zelleVeraendern((short)0, (short)6, L1x7.getText());
        control.main.zelleVeraendern((short)0, (short)7, L1x8.getText());
        control.main.zelleVeraendern((short)0, (short)8, L1x9.getText());
        
        control.main.zelleVeraendern((short)1, (short)0, L2x1.getText());
        control.main.zelleVeraendern((short)1, (short)1, L2x2.getText());
        control.main.zelleVeraendern((short)1, (short)2, L2x3.getText());
        control.main.zelleVeraendern((short)1, (short)3, L2x4.getText());
        control.main.zelleVeraendern((short)1, (short)4, L2x5.getText());
        control.main.zelleVeraendern((short)1, (short)5, L2x6.getText());
        control.main.zelleVeraendern((short)1, (short)6, L2x7.getText());
        control.main.zelleVeraendern((short)1, (short)7, L2x8.getText());
        control.main.zelleVeraendern((short)1, (short)8, L2x9.getText());
        
        control.main.zelleVeraendern((short)2, (short)0, L3x1.getText());
        control.main.zelleVeraendern((short)2, (short)1, L3x2.getText());
        control.main.zelleVeraendern((short)2, (short)2, L3x3.getText());
        control.main.zelleVeraendern((short)2, (short)3, L3x4.getText());
        control.main.zelleVeraendern((short)2, (short)4, L3x5.getText());
        control.main.zelleVeraendern((short)2, (short)5, L3x6.getText());
        control.main.zelleVeraendern((short)2, (short)6, L3x7.getText());
        control.main.zelleVeraendern((short)2, (short)7, L3x8.getText());
        control.main.zelleVeraendern((short)2, (short)8, L3x9.getText());
        
        control.main.zelleVeraendern((short)3, (short)0, L4x1.getText());
        control.main.zelleVeraendern((short)3, (short)1, L4x2.getText());
        control.main.zelleVeraendern((short)3, (short)2, L4x3.getText());
        control.main.zelleVeraendern((short)3, (short)3, L4x4.getText());
        control.main.zelleVeraendern((short)3, (short)4, L4x5.getText());
        control.main.zelleVeraendern((short)3, (short)5, L4x6.getText());
        control.main.zelleVeraendern((short)3, (short)6, L4x7.getText());
        control.main.zelleVeraendern((short)3, (short)7, L4x8.getText());
        control.main.zelleVeraendern((short)3, (short)8, L4x9.getText());
        
        control.main.zelleVeraendern((short)4, (short)0, L5x1.getText());
        control.main.zelleVeraendern((short)4, (short)1, L5x2.getText());
        control.main.zelleVeraendern((short)4, (short)2, L5x3.getText());
        control.main.zelleVeraendern((short)4, (short)3, L5x4.getText());
        control.main.zelleVeraendern((short)4, (short)4, L5x5.getText());
        control.main.zelleVeraendern((short)4, (short)5, L5x6.getText());
        control.main.zelleVeraendern((short)4, (short)6, L5x7.getText());
        control.main.zelleVeraendern((short)4, (short)7, L5x8.getText());
        control.main.zelleVeraendern((short)4, (short)8, L5x9.getText());
        
        control.main.zelleVeraendern((short)5, (short)0, L6x1.getText());
        control.main.zelleVeraendern((short)5, (short)1, L6x2.getText());
        control.main.zelleVeraendern((short)5, (short)2, L6x3.getText());
        control.main.zelleVeraendern((short)5, (short)3, L6x4.getText());
        control.main.zelleVeraendern((short)5, (short)4, L6x5.getText());
        control.main.zelleVeraendern((short)5, (short)5, L6x6.getText());
        control.main.zelleVeraendern((short)5, (short)6, L6x7.getText());
        control.main.zelleVeraendern((short)5, (short)7, L6x8.getText());
        control.main.zelleVeraendern((short)5, (short)8, L6x9.getText());
        
        control.main.zelleVeraendern((short)6, (short)0, L7x1.getText());
        control.main.zelleVeraendern((short)6, (short)1, L7x2.getText());
        control.main.zelleVeraendern((short)6, (short)2, L7x3.getText());
        control.main.zelleVeraendern((short)6, (short)3, L7x4.getText());
        control.main.zelleVeraendern((short)6, (short)4, L7x5.getText());
        control.main.zelleVeraendern((short)6, (short)5, L7x6.getText());
        control.main.zelleVeraendern((short)6, (short)6, L7x7.getText());
        control.main.zelleVeraendern((short)6, (short)7, L7x8.getText());
        control.main.zelleVeraendern((short)6, (short)8, L7x9.getText());
        
        control.main.zelleVeraendern((short)7, (short)0, L8x1.getText());
        control.main.zelleVeraendern((short)7, (short)1, L8x2.getText());
        control.main.zelleVeraendern((short)7, (short)2, L8x3.getText());
        control.main.zelleVeraendern((short)7, (short)3, L8x4.getText());
        control.main.zelleVeraendern((short)7, (short)4, L8x5.getText());
        control.main.zelleVeraendern((short)7, (short)5, L8x6.getText());
        control.main.zelleVeraendern((short)7, (short)6, L8x7.getText());
        control.main.zelleVeraendern((short)7, (short)7, L8x8.getText());
        control.main.zelleVeraendern((short)7, (short)8, L8x9.getText());
        
        control.main.zelleVeraendern((short)8, (short)0, L9x1.getText());
        control.main.zelleVeraendern((short)8, (short)1, L9x2.getText());
        control.main.zelleVeraendern((short)8, (short)2, L9x3.getText());
        control.main.zelleVeraendern((short)8, (short)3, L9x4.getText());
        control.main.zelleVeraendern((short)8, (short)4, L9x5.getText());
        control.main.zelleVeraendern((short)8, (short)5, L9x6.getText());
        control.main.zelleVeraendern((short)8, (short)6, L9x7.getText());
        control.main.zelleVeraendern((short)8, (short)7, L9x8.getText());
        control.main.zelleVeraendern((short)8, (short)8, L9x9.getText());
        
        control.main.sudokuErstellen();
        control.main.sudokuLoesen();
    }//GEN-LAST:event_LösenImpActionPerformed





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImportImp;
    private javax.swing.JTextPane L1x1;
    private javax.swing.JTextPane L1x2;
    private javax.swing.JTextPane L1x3;
    private javax.swing.JTextPane L1x4;
    private javax.swing.JTextPane L1x5;
    private javax.swing.JTextPane L1x6;
    private javax.swing.JTextPane L1x7;
    private javax.swing.JTextPane L1x8;
    private javax.swing.JTextPane L1x9;
    private javax.swing.JTextPane L2x1;
    private javax.swing.JTextPane L2x2;
    private javax.swing.JTextPane L2x3;
    private javax.swing.JTextPane L2x4;
    private javax.swing.JTextPane L2x5;
    private javax.swing.JTextPane L2x6;
    private javax.swing.JTextPane L2x7;
    private javax.swing.JTextPane L2x8;
    private javax.swing.JTextPane L2x9;
    private javax.swing.JTextPane L3x1;
    private javax.swing.JTextPane L3x2;
    private javax.swing.JTextPane L3x3;
    private javax.swing.JTextPane L3x4;
    private javax.swing.JTextPane L3x5;
    private javax.swing.JTextPane L3x6;
    private javax.swing.JTextPane L3x7;
    private javax.swing.JTextPane L3x8;
    private javax.swing.JTextPane L3x9;
    private javax.swing.JTextPane L4x1;
    private javax.swing.JTextPane L4x2;
    private javax.swing.JTextPane L4x3;
    private javax.swing.JTextPane L4x4;
    private javax.swing.JTextPane L4x5;
    private javax.swing.JTextPane L4x6;
    private javax.swing.JTextPane L4x7;
    private javax.swing.JTextPane L4x8;
    private javax.swing.JTextPane L4x9;
    private javax.swing.JTextPane L5x1;
    private javax.swing.JTextPane L5x2;
    private javax.swing.JTextPane L5x3;
    private javax.swing.JTextPane L5x4;
    private javax.swing.JTextPane L5x5;
    private javax.swing.JTextPane L5x6;
    private javax.swing.JTextPane L5x7;
    private javax.swing.JTextPane L5x8;
    private javax.swing.JTextPane L5x9;
    private javax.swing.JTextPane L6x1;
    private javax.swing.JTextPane L6x2;
    private javax.swing.JTextPane L6x3;
    private javax.swing.JTextPane L6x4;
    private javax.swing.JTextPane L6x5;
    private javax.swing.JTextPane L6x6;
    private javax.swing.JTextPane L6x7;
    private javax.swing.JTextPane L6x8;
    private javax.swing.JTextPane L6x9;
    private javax.swing.JTextPane L7x1;
    private javax.swing.JTextPane L7x2;
    private javax.swing.JTextPane L7x3;
    private javax.swing.JTextPane L7x4;
    private javax.swing.JTextPane L7x5;
    private javax.swing.JTextPane L7x6;
    private javax.swing.JTextPane L7x7;
    private javax.swing.JTextPane L7x8;
    private javax.swing.JTextPane L7x9;
    private javax.swing.JTextPane L8x1;
    private javax.swing.JTextPane L8x2;
    private javax.swing.JTextPane L8x3;
    private javax.swing.JTextPane L8x4;
    private javax.swing.JTextPane L8x5;
    private javax.swing.JTextPane L8x6;
    private javax.swing.JTextPane L8x7;
    private javax.swing.JTextPane L8x8;
    private javax.swing.JTextPane L8x9;
    private javax.swing.JTextPane L9x1;
    private javax.swing.JTextPane L9x2;
    private javax.swing.JTextPane L9x3;
    private javax.swing.JTextPane L9x4;
    private javax.swing.JTextPane L9x5;
    private javax.swing.JTextPane L9x6;
    private javax.swing.JTextPane L9x7;
    private javax.swing.JTextPane L9x8;
    private javax.swing.JTextPane L9x9;
    private javax.swing.JButton LösenImp;
    private javax.swing.JButton ZurückImp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
